/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      // Semantic colors via CSS variables — use rgb() format for Tailwind opacity support
      canvas: "rgb(var(--color-canvas) / <alpha-value>)",
      surface: "rgb(var(--color-surface) / <alpha-value>)",
      "surface-alt": "rgb(var(--color-surface-alt) / <alpha-value>)",
      ink: "rgb(var(--color-ink) / <alpha-value>)",
      "ink-soft": "rgb(var(--color-ink-soft) / <alpha-value>)",
      muted: "rgb(var(--color-muted) / <alpha-value>)",
      hairline: "rgb(var(--color-hairline) / <alpha-value>)",
      "hairline-soft": "rgb(var(--color-hairline-soft) / <alpha-value>)",
      "hairline-strong": "rgb(var(--color-hairline-strong) / <alpha-value>)",
      cream: "rgb(var(--color-cream) / <alpha-value>)",
      "cream-deeper": "rgb(var(--color-cream-deeper) / <alpha-value>)",
      "beige-deep": "rgb(var(--color-beige-deep) / <alpha-value>)",
      slate: "rgb(var(--color-slate) / <alpha-value>)",
      steel: "rgb(var(--color-steel) / <alpha-value>)",
      stone: "rgb(var(--color-stone) / <alpha-value>)",
      // Brand (fixed — same in both modes)
      primary: "#fa520f",
      "primary-deep": "#cc3a05",
      "on-primary": "#ffffff",
      // Sunshine gradient (fixed)
      "sunshine-300": "#ffd06a",
      "sunshine-500": "#ffb83e",
      "sunshine-700": "#ffa110",
      "sunshine-800": "#ff8105",
      "sunshine-900": "#ff8a00",
      "yellow-saturated": "#ffd900",
      // Fixed utility colors
      "on-dark": "#ffffff",
      "on-dark-muted": "#a8a8a8",
      "surface-code": "#1c1c1e",
      // Semantic
      link: "#fa520f",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fontFamily: {
      display: ["Poppins", "Inter", "sans-serif"],
      body: ["Poppins", "Inter", "sans-serif"],
      mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
    },
    fontSize: {
      hero: [
        "84px",
        { lineHeight: "1.05", letterSpacing: "-1.5px", fontWeight: "600" },
      ],
      "display-lg": [
        "64px",
        { lineHeight: "1.10", letterSpacing: "-1px", fontWeight: "600" },
      ],
      "heading-1": [
        "52px",
        { lineHeight: "1.15", letterSpacing: "-0.5px", fontWeight: "600" },
      ],
      "heading-2": [
        "36px",
        { lineHeight: "1.20", letterSpacing: "-0.5px", fontWeight: "500" },
      ],
      "heading-3": ["28px", { lineHeight: "1.25", fontWeight: "500" }],
      "heading-4": ["22px", { lineHeight: "1.30", fontWeight: "500" }],
      "heading-5": ["18px", { lineHeight: "1.40", fontWeight: "500" }],
      subtitle: ["18px", { lineHeight: "1.50", fontWeight: "400" }],
      "body-md": ["16px", { lineHeight: "1.55", fontWeight: "400" }],
      "body-md-medium": ["16px", { lineHeight: "1.55", fontWeight: "500" }],
      "body-sm": ["14px", { lineHeight: "1.50", fontWeight: "400" }],
      "body-sm-medium": ["14px", { lineHeight: "1.50", fontWeight: "500" }],
      caption: ["13px", { lineHeight: "1.40", fontWeight: "400" }],
      "caption-bold": ["13px", { lineHeight: "1.40", fontWeight: "600" }],
      micro: ["12px", { lineHeight: "1.40", fontWeight: "500" }],
      "micro-uppercase": [
        "11px",
        { lineHeight: "1.40", letterSpacing: "1px", fontWeight: "600" },
      ],
      button: ["14px", { lineHeight: "1.30", fontWeight: "500" }],
      stat: [
        "56px",
        { lineHeight: "1.10", letterSpacing: "-1px", fontWeight: "600" },
      ],
      code: ["14px", { lineHeight: "1.50", fontWeight: "400" }],
    },
    borderRadius: {
      none: "0px",
      xs: "4px",
      sm: "6px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
    },
    spacing: {
      0: "0px",
      xxs: "4px",
      xs: "8px",
      sm: "12px",
      md: "16px",
      lg: "20px",
      xl: "24px",
      "2xl": "32px",
      "3xl": "40px",
      "section-sm": "48px",
      section: "64px",
      "section-lg": "96px",
      hero: "120px",
    },
    extend: {
      minHeight: {
        touch: "44px",
      },
      minWidth: {
        touch: "44px",
      },
      boxShadow: {
        subtle: "0 1px 2px rgba(0,0,0,0.04)",
        card: "0 4px 12px rgba(0,0,0,0.04)",
        mockup: "0 12px 24px -4px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};
