export interface Errand {
  id: string;
  type: string;
  description: string;
  origin_address: string;
  origin_address_input: string | null;
  origin_address_resolved: string | null;
  origin_lat: number | null;
  origin_lng: number | null;
  origin_exact_lat: number | null;
  origin_exact_lng: number | null;
  origin_routable_lat: number | null;
  origin_routable_lng: number | null;
  origin_instructions: string | null;
  origin_confirmed: number;
  destination_address: string;
  destination_address_input: string | null;
  destination_address_resolved: string | null;
  destination_lat: number | null;
  destination_lng: number | null;
  destination_exact_lat: number | null;
  destination_exact_lng: number | null;
  destination_routable_lat: number | null;
  destination_routable_lng: number | null;
  destination_instructions: string | null;
  destination_confirmed: number;
  fare: number;
  platform_commission: number;
  rider_earnings: number;
  rider_id: string | null;
  rider_name: string | null;
  motorcycle_plate: string | null;
  status: string;
  payment_method: string;
  pin: string | null;
  requested_at: string;
  accepted_at: string | null;
  picked_up_at: string | null;
  delivered_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}
